sudo: false

language: php

php:
  - 7
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text
